const abi = [{"inputs":[{"internalType":"address","name":"_pandoWallet","type":"address"},{"internalType":"uint256","name":"_pandoPercentage","type":"uint256"}],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"NFT","type":"address"},{"indexed":true,"internalType":"uint256","name":"id","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"price","type":"uint256"},{"indexed":false,"internalType":"address","name":"seller","type":"address"}],"name":"EscrowCreated","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"NFT","type":"address"},{"indexed":true,"internalType":"uint256","name":"id","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"price","type":"uint256"},{"indexed":false,"internalType":"address","name":"seller","type":"address"},{"indexed":false,"internalType":"address","name":"buyer","type":"address"}],"name":"EscrowFufilled","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"NFT","type":"address"},{"indexed":true,"internalType":"uint256","name":"id","type":"uint256"},{"indexed":false,"internalType":"enum Escrow5.State","name":"","type":"uint8"}],"name":"StateChange","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"sellerAmount","type":"uint256"},{"indexed":false,"internalType":"uint256","name":"pandoWalletAmount","type":"uint256"}],"name":"transferAmounts","type":"event"},{"inputs":[],"name":"balanceInContract","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"NFT","type":"address"},{"internalType":"uint256","name":"index","type":"uint256"}],"name":"confirmDelivery","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"NFT","type":"address"},{"internalType":"uint256","name":"index","type":"uint256"}],"name":"confirmPayment","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[{"internalType":"address","name":"NFT","type":"address"},{"internalType":"uint256","name":"index","type":"uint256"},{"internalType":"uint256","name":"price","type":"uint256"}],"name":"createEscrow","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"NFT","type":"address"},{"internalType":"uint256","name":"index","type":"uint256"}],"name":"declinePendingOffer","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"pandoWallet","outputs":[{"internalType":"address payable","name":"","type":"address"}],"stateMutability":"view","type":"function"}]

const escrowContract = web3 => {
    return new web3.eth.Contract(
        abi, "0x720f827eC05D1E1B5A267585633348b8e117e941"
    )
}


export default escrowContract